# -*- coding: utf-8 -*-
"""Currency Notes Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VaLkOGhVtsxHdjLAY49JTZHaOeac3ZhB

## Pre-Processing Dataset
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

cd /gdrive/MyDrive/Major Project/Currency Notes Recognition

"""### Creating final dataset folder"""

import os
directory = "final_dataset"
parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition"
path = os.path.join(parent_dir, directory)

os.mkdir(path)

"""### Creating Test, training and Validation folders"""

directory = "test"
parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset"
path = os.path.join(parent_dir, directory)

os.mkdir(path)

directory = "training"
parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset"
path = os.path.join(parent_dir, directory)

os.mkdir(path)

directory = "validation"
parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset"
path = os.path.join(parent_dir, directory)

os.mkdir(path)

"""## Test Data"""

import shutil
import os

src_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/Indian_currency_dataset_v1/test'
dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/test'

files = os.listdir(src_dir)

print(files)

for f in files:
    shutil.copy(src_dir + '/' + f, dest_dir)

"""## Validation Data

### Creating categories
"""

denominations = ['10','20','50','100','200','500','2000','Background']

parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/validation"

for x in denominations:
  directory = x
  path = os.path.join(parent_dir, directory)
  os.mkdir(path)

src_dir = ['/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/Indian_currency_dataset_v1/validation',
           '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/indian_currency_new/validation']

dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/validation'

"""### Copying files to final dataset"""

for y in src_dir:
  dir = [x[0] for x in os.walk(y)]
  
  for cur in dir:
    category = cur.split('/')

    if category[-1] != 'validation':
      files = os.listdir(cur)

      for f in files:
        shutil.copy(cur + '/' + f, dest_dir + '/' + category[-1])

"""### Renaming files"""

dir = [x[0] for x in os.walk(dest_dir)]

for cur in dir:
    category = cur.split('/')

    if category[-1] != 'validation':
      files = os.listdir(cur)

      index = 1
      deno = category[-1]

      for f in files:
        os.rename(cur + '/' + f,cur + '/' + deno + '_' + str(index))
        index += 1

"""## Training data

### Creating categories
"""

denominations = ['10','20','50','100','200','500','2000','Background']

parent_dir = "/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training"

for x in denominations:
  directory = x
  path = os.path.join(parent_dir, directory)
  os.mkdir(path)

src_dir = ['/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/Indian_currency_dataset_v1/training',
           '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/indian_currency_new/training']

dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training'

"""### Copying files to final dataset"""

dir = [x[0] for x in os.walk(src_dir[0])]
dir

for y in src_dir:
  dir = [x[0] for x in os.walk(y)]
  
  for cur in dir:
    category = cur.split('/')

    if category[-1] != 'training':
      files = os.listdir(cur)

      for f in files:
        shutil.copy(cur + '/' + f, dest_dir + '/' + category[-1])

"""### Renaming Files"""

dir = [x[0] for x in os.walk(dest_dir)]

for cur in dir:
    category = cur.split('/')

    if category[-1] != 'training':
      files = os.listdir(cur)

      index = 1
      deno = category[-1]

      for f in files:
        os.rename(cur + '/' + f,cur + '/' + deno + '_' + str(index))
        index += 1

"""## Currency dataset to final_dataset training

### 50
"""

src_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/currency_dataset/fifty'
dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training/50'

files = os.listdir(src_dir)

index = len(os.listdir(dest_dir)) + 1
deno = '50'

for f in files:
    shutil.copy(src_dir + '/' + f, dest_dir)
    os.rename(src_dir + '/' + f, dest_dir + '/' + deno + '_' + str(index))
    index += 1

"""### 20"""

src_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/currency_dataset/twenty'
dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training/20'

files = os.listdir(src_dir)

index = len(os.listdir(dest_dir)) + 1
deno = '20'

for f in files:
    shutil.copy(src_dir + '/' + f, dest_dir)
    os.rename(src_dir + '/' + f, dest_dir + '/' + deno + '_' + str(index))
    index += 1

"""### 10"""

src_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/currency_dataset/ten'
dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training/10'

files = os.listdir(src_dir)

index = len(os.listdir(dest_dir)) + 1
deno = '10'

for f in files:
    shutil.copy(src_dir + '/' + f, dest_dir)
    os.rename(src_dir + '/' + f, dest_dir + '/' + deno + '_' + str(index))
    index += 1

"""### 100"""

src_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/Datasets/currency_dataset/hundred'
dest_dir = '/gdrive/MyDrive/Major Project/Currency Notes Recognition/final_dataset/training/100'

files = os.listdir(src_dir)

index = len(os.listdir(dest_dir)) + 1
deno = '100'

for f in files:
    shutil.copy(src_dir + '/' + f, dest_dir)
    os.rename(src_dir + '/' + f, dest_dir + '/' + deno + '_' + str(index))
    index += 1

